title: Bérénice Batut
description: Website of Bérénice Batut

url: http://bebatut-research.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Research
   url: /research
 - title: Teaching
   url: /teaching
 - title: Publications
   url: /publications
 - title: Talks
   url: /talks

social:
   github: bebatut
   twitter: bebatut
   email: berenice.batut@gmail.com
   researchgate: Berenice_Batut
   linkedin: berenicebatut

google_analytics: 
